- id: m0rninglight
  alias: Turn On Morning light
  trigger:
    platform: time
    at: 07:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: homeassistant.turn_on
    entity_id: scene.morning_light
- id: sund0wn
  alias: Sundown Patio
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  action:
  - service: homeassistant.turn_on
    entity_id: switch.rear_patio_lights
  - service: homeassistant.turn_on
    entity_id: scene.working_at_night
- id: sunup
  alias: Sunup Patio
  trigger:
    platform: sun
    event: sunrise
    offset: +00:30:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.rear_patio_lights
- id: sm0ketime
  alias: PAX DETECTED
  trigger:
  - entity_id: sensor.pax3
    from: not_home
    platform: state
    to: game_room
  action:
  - data:
      brightness: 255
      color_name: green
      cycles: 3
      entity_id: light.game_room_lamp, light.game_room_ceiling
      mode: breathe
      period: 10
      power_on: false
    service: lifx.effect_pulse
- id: b0b
  alias: Bob is here
  trigger:
  - entity_id: device_tracker.bob_s_iphone
    from: not_home
    platform: state
    to: home
  action:
    service: script.turn_on
    entity_id: script.bob_is_here
- id: device0ffline
  alias: Tracked Device Offline Notification
  trigger:
    platform: state
    entity_id: device_tracker.backupnas, device_tracker.frontap, device_tracker.winkrelay,
      device_tracker.huehub, device_tracker.winkhub, device_tracker.garagecam, device_tracker.lifx1,
      device_tracker.lifx2, device_tracker.lifx3, device_tracker.lifx4, device_tracker.lifx5,
      device_tracker.lifx6, device_tracker.sonosone, device_tracker.pihole, device_tracker.primarynas,
      device_tracker.livingroomcam, device_tracker.rearap, device_tracker.sonosamp,
      device_tracker.sonosplay5, device_tracker.studioap, device_tracker.studioprinter,
      device_tracker.unifi, device_tracker.website, device_tracker.winserver
    from: home
    to: not_home
  action:
    service: notify.email_alerts
    data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has gone offline.

        '
      title: '[ALERT] {{ trigger.to_state.attributes.friendly_name }} Offline'
- id: device0nline
  alias: Tracked Device Online Notification
  trigger:
    platform: state
    entity_id: device_tracker.backupnas, device_tracker.frontap, device_tracker.winkrelay,
      device_tracker.huehub, device_tracker.winkhub, device_tracker.garagecam, device_tracker.lifx1,
      device_tracker.lifx2, device_tracker.lifx3, device_tracker.lifx4, device_tracker.lifx5,
      device_tracker.lifx6, device_tracker.sonosone, device_tracker.pihole, device_tracker.primarynas,
      device_tracker.livingroomcam, device_tracker.rearap, device_tracker.sonosamp,
      device_tracker.sonosplay5, device_tracker.studioap, device_tracker.studioprinter,
      device_tracker.unifi, device_tracker.website, device_tracker.winserver
    from: not_home
    to: home
  action:
    service: notify.email_alerts
    data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has come back online.

        '
      title: '[RESOLVED] {{ trigger.to_state.attributes.friendly_name }} Online'
- id: bed3fan0ff
  alias: Turn Off Bedroom 3 Fan
  trigger:
    platform: time
    at: 09:15:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.bedroom_3_fan
- id: s3tth3m3
  alias: Automation for Theme HA Restart
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: night
    service: frontend.set_theme
  initial_state: true
- id: abode_and_blink_armed
  alias: Blink Arms With Abode
  trigger:
  - entity_id: alarm_control_panel.abode_alarm
    from: disarmed
    platform: state
    to: armed_home
  action:
  - service: homeassistant.turn_on
    entity_id: scene.arm_blink
- id: abode_and_blink_disarmed
  alias: Blink Disarms With Abode
  trigger:
  - entity_id: alarm_control_panel.abode_alarm
    from: armed_home
    platform: state
    to: disarmed
  action:
  - service: homeassistant.turn_on
    entity_id: scene.disarm_blink
- id: entertaining_colors
  alias: Entertaining At Night Color Loop
  trigger:
  - event_data:
      domain: scene
      service: turn_on
      service_data:
        entity_id: scene.entertaining_at_night
    event_type: call_service
    platform: event
  action:
  - data:
      brightness: 255
      change: 100
      period: 30
      spread: 100
      transition: 10
    entity_id: light.kitchen_overhead_lamp
    service: lifx.effect_colorloop
  - service: homeassistant.turn_on
    entity_id: light.living_room_lamp
    data:
      effect: Random
      brightness: 127
