esphome:
  name: bedroom_1_ceiling
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom 1 Ceiling"
    password: !secret esphome_fallback_pw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sm16716:
  data_pin: GPIO4
  clock_pin: GPIO5
  num_channels: 5
  num_chips: 1

output:
  - platform: sm16716
    id: output_red
    channel: 0
  - platform: sm16716
    id: output_green
    channel: 1
  - platform: sm16716
    id: output_blue
    channel: 2
  - platform: sm16716
    id: output_warm_white
    channel: 3
  - platform: sm16716
    id: output_cold_white
    channel: 4

light:
  - platform: rgbww
    name: "Bedroom 1 Ceiling"
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
    effects:
      - random:
      - random:
          name: Random (Fast)
          transition_length: 1s
          update_interval: 1s
      - strobe:
      - strobe:
          name: Strobe (Police)
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 250ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              white: 0%
              duration: 250ms
      - flicker:
      - flicker:
          name: Flicker (Intense)
          alpha: 80%
          intensity: 5%
      
