esphome:
  name: kitchen_downlight_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Downlight 1"
    password: !secret esphome_fallback_pw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: esp8266_pwm
    pin: 14
    id: output_blue
  - platform: esp8266_pwm
    pin: 12
    id: output_green
  - platform: esp8266_pwm
    pin: 4
    id: output_red
  - platform: esp8266_pwm
    pin: 5
    id: output_coldwhite
  - platform: esp8266_pwm
    pin: 13
    id: output_warmwhite

light:
  - platform: rgbww
    name: kitchen_downlight_1
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_coldwhite
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: true
    constant_brightness: true
    effects:
      - random:
      - random:
          name: Random (Fast)
          transition_length: 1s
          update_interval: 1s
      - strobe:
      - strobe:
          name: Strobe (Police)
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 250ms
            - state: False
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              white: 0%
              duration: 250ms
      - flicker:
      - flicker:
          name: Flicker (Intense)
          alpha: 80%
          intensity: 5%
    