esphome:
  name: rear_patio_lights
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rear Patio Lights"
    password: !secret esphome_fallback_pw

captive_portal:

logger:

api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: "Rear Patio Lights Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: led
    pin:
      number: GPIO12
      inverted: true
      
  - platform: gpio
    name: "Rear Patio Lights"
    pin: GPIO14
    id: relay

    on_turn_on:
      - switch.turn_on: led
      
    on_turn_off:
      - switch.turn_off: led